[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
spin = "0.9.4"
uart_16550 = "0.2.18"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]